require 'fileutils'

assets = %w[
  ape_chef_angry-0.png
  ape_chef_angry-1.png
  ape_chef_angry-10.png
  ape_chef_angry-11.png
  ape_chef_angry-12.png
  ape_chef_angry-13.png
  ape_chef_angry-14.png
  ape_chef_angry-15.png
  ape_chef_angry-2.png
  ape_chef_angry-3.png
  ape_chef_angry-4.png
  ape_chef_angry-5.png
  ape_chef_angry-6.png
  ape_chef_angry-7.png
  ape_chef_angry-8.png
  ape_chef_angry-9.png
  ape_chef_drag-0.png
  ape_chef_drag-1.png
  ape_chef_drag-2.png
  ape_chef_drag-3.png
  ape_chef_eat-0.png
  ape_chef_eat-1.png
  ape_chef_eat-10.png
  ape_chef_eat-11.png
  ape_chef_eat-12.png
  ape_chef_eat-13.png
  ape_chef_eat-14.png
  ape_chef_eat-15.png
  ape_chef_eat-16.png
  ape_chef_eat-17.png
  ape_chef_eat-18.png
  ape_chef_eat-19.png
  ape_chef_eat-2.png
  ape_chef_eat-20.png
  ape_chef_eat-21.png
  ape_chef_eat-22.png
  ape_chef_eat-23.png
  ape_chef_eat-24.png
  ape_chef_eat-25.png
  ape_chef_eat-26.png
  ape_chef_eat-27.png
  ape_chef_eat-28.png
  ape_chef_eat-29.png
  ape_chef_eat-3.png
  ape_chef_eat-30.png
  ape_chef_eat-31.png
  ape_chef_eat-4.png
  ape_chef_eat-5.png
  ape_chef_eat-6.png
  ape_chef_eat-7.png
  ape_chef_eat-8.png
  ape_chef_eat-9.png
  ape_chef_front_still-0.png
  ape_chef_front_still-1.png
  ape_chef_front_still-2.png
  ape_chef_front_still-3.png
  ape_chef_front_still-4.png
  ape_chef_front_still-5.png
  ape_chef_front_still-6.png
  ape_chef_front_still-7.png
  ape_chef_front-0.png
  ape_chef_front-1.png
  ape_chef_front-10.png
  ape_chef_front-11.png
  ape_chef_front-12.png
  ape_chef_front-13.png
  ape_chef_front-14.png
  ape_chef_front-15.png
  ape_chef_front-16.png
  ape_chef_front-17.png
  ape_chef_front-18.png
  ape_chef_front-19.png
  ape_chef_front-2.png
  ape_chef_front-20.png
  ape_chef_front-21.png
  ape_chef_front-22.png
  ape_chef_front-23.png
  ape_chef_front-24.png
  ape_chef_front-25.png
  ape_chef_front-26.png
  ape_chef_front-27.png
  ape_chef_front-28.png
  ape_chef_front-29.png
  ape_chef_front-3.png
  ape_chef_front-30.png
  ape_chef_front-31.png
  ape_chef_front-32.png
  ape_chef_front-4.png
  ape_chef_front-5.png
  ape_chef_front-6.png
  ape_chef_front-7.png
  ape_chef_front-8.png
  ape_chef_front-9.png
  ape_chef_lateral-0.png
  ape_chef_lateral-1.png
  ape_chef_lateral-2.png
  ape_chef_lateral-3.png
  ape_chef_sleep-0.png
  ape_chef_sleep-1.png
  ape_chef_sleep-2.png
  ape_chef_sleep-3.png
  ape_chef_sleep-4.png
  ape_chef_sleep-5.png
  ape_chef_sleep-6.png
  ape_chef_sleep-7.png
  ape_chef_walk-0.png
  ape_chef_walk-1.png
  ape_chef_walk-2.png
  ape_chef_walk-3.png
  ape_chef_walk-4.png
  ape_chef_walk-5.png
  ape_chef_walk-6.png
  ape_chef_walk-7.png
  ape_front-0.png
  ape_walk-0.png
  ape_walk-1.png
  ape_walk-2.png
  ape_walk-3.png
  ape_walk-4.png
  ape_walk-5.png
  ape_walk-6.png
  ape_walk-7.png
  betta_front-0.png
  cat_blue_24_front-0.png
  cat_blue_24_front-1.png
  cat_blue_24_front-2.png
  cat_blue_24_front-3.png
  cat_blue_24_front-4.png
  cat_blue_24_front-5.png
  cat_blue_24_front-6.png
  cat_blue_24_front-7.png
  cat_blue_24_lateral-0.png
  cat_blue_24_lateral-1.png
  cat_blue_24_lateral-2.png
  cat_blue_24_lateral-3.png
  cat_blue_24_lateral-4.png
  cat_blue_24_lateral-5.png
  cat_blue_24_lateral-6.png
  cat_blue_24_lateral-7.png
  cat_blue_24_walk-0.png
  cat_blue_24_walk-1.png
  cat_blue_24_walk-2.png
  cat_blue_24_walk-3.png
  cat_blue_24_walk-4.png
  cat_blue_24_walk-5.png
  cat_blue_24_walk-6.png
  cat_blue_24_walk-7.png
  cat_blue_angry-0.png
  cat_blue_angry-1.png
  cat_blue_angry-2.png
  cat_blue_angry-3.png
  cat_blue_angry-4.png
  cat_blue_angry-5.png
  cat_blue_angry-6.png
  cat_blue_angry-7.png
  cat_blue_chainsaw_man-0.png
  cat_blue_chainsaw_man-1.png
  cat_blue_chainsaw_man-2.png
  cat_blue_chainsaw_man-3.png
  cat_blue_chainsaw_man-4.png
  cat_blue_chainsaw_man-5.png
  cat_blue_drag-0.png
  cat_blue_drag-1.png
  cat_blue_drag-2.png
  cat_blue_drag-3.png
  cat_blue_drag-4.png
  cat_blue_drag-5.png
  cat_blue_drag-6.png
  cat_blue_eat-0.png
  cat_blue_eat-1.png
  cat_blue_eat-2.png
  cat_blue_eat-3.png
  cat_blue_eat-4.png
  cat_blue_eat-5.png
  cat_blue_eat-6.png
  cat_blue_eat-7.png
  cat_blue_eat-8.png
  cat_blue_front-0.png
  cat_blue_front-1.png
  cat_blue_front-2.png
  cat_blue_front-3.png
  cat_blue_front-4.png
  cat_blue_front-5.png
  cat_blue_hammer-0.png
  cat_blue_hammer-1.png
  cat_blue_hammer-2.png
  cat_blue_hammer-3.png
  cat_blue_hammer-4.png
  cat_blue_hammer-5.png
  cat_blue_helmet_and_tape-0.png
  cat_blue_helmet_and_tape-1.png
  cat_blue_helmet_and_tape-2.png
  cat_blue_helmet_and_tape-3.png
  cat_blue_helmet_and_tape-4.png
  cat_blue_helmet_and_tape-5.png
  cat_blue_helmet-0.png
  cat_blue_helmet-1.png
  cat_blue_helmet-2.png
  cat_blue_helmet-3.png
  cat_blue_helmet-4.png
  cat_blue_helmet-5.png
  cat_blue_idle-0.png
  cat_blue_idle-1.png
  cat_blue_idle-2.png
  cat_blue_idle-3.png
  cat_blue_idle-4.png
  cat_blue_idle-5.png
  cat_blue_lateral-0.png
  cat_blue_lateral-1.png
  cat_blue_lateral-2.png
  cat_blue_lateral-3.png
  cat_blue_lateral-4.png
  cat_blue_lateral-5.png
  cat_blue_love-0.png
  cat_blue_love-1.png
  cat_blue_love-2.png
  cat_blue_love-3.png
  cat_blue_love-4.png
  cat_blue_love-5.png
  cat_blue_phonecall-0.png
  cat_blue_phonecall-1.png
  cat_blue_phonecall-2.png
  cat_blue_phonecall-3.png
  cat_blue_phonecall-4.png
  cat_blue_phonecall-5.png
  cat_blue_sleep-0.png
  cat_blue_sleep-1.png
  cat_blue_sleep-2.png
  cat_blue_sleep-3.png
  cat_blue_sleep-4.png
  cat_blue_sleep-5.png
  cat_blue_walk-0.png
  cat_blue_walk-1.png
  cat_blue_walk-2.png
  cat_blue_walk-3.png
  cat_blue_walk-4.png
  cat_blue_walk-5.png
  cat_blue_walk-6.png
  cat_blue_walk-7.png
  cat_blue_worried_knife-0.png
  cat_blue_worried_knife-1.png
  cat_blue_worried_knife-2.png
  cat_blue_worried_knife-3.png
  cat_blue_worried_knife-4.png
  cat_blue_worried_knife-5.png
  cat_blue_worried-0.png
  cat_blue_worried-1.png
  cat_blue_worried-2.png
  cat_blue_worried-3.png
  cat_blue_worried-4.png
  cat_blue_worried-5.png
  cat_front-0.png
  crow_front-0.png
  frog_front-0.png
  panda_front-0.png
  sheep_black_eat-0.png
  sheep_black_eat-1.png
  sheep_black_eat-10.png
  sheep_black_eat-11.png
  sheep_black_eat-12.png
  sheep_black_eat-13.png
  sheep_black_eat-14.png
  sheep_black_eat-15.png
  sheep_black_eat-16.png
  sheep_black_eat-17.png
  sheep_black_eat-18.png
  sheep_black_eat-19.png
  sheep_black_eat-2.png
  sheep_black_eat-20.png
  sheep_black_eat-21.png
  sheep_black_eat-22.png
  sheep_black_eat-23.png
  sheep_black_eat-24.png
  sheep_black_eat-25.png
  sheep_black_eat-26.png
  sheep_black_eat-27.png
  sheep_black_eat-28.png
  sheep_black_eat-29.png
  sheep_black_eat-3.png
  sheep_black_eat-30.png
  sheep_black_eat-31.png
  sheep_black_eat-32.png
  sheep_black_eat-33.png
  sheep_black_eat-34.png
  sheep_black_eat-35.png
  sheep_black_eat-36.png
  sheep_black_eat-37.png
  sheep_black_eat-4.png
  sheep_black_eat-5.png
  sheep_black_eat-6.png
  sheep_black_eat-7.png
  sheep_black_eat-8.png
  sheep_black_eat-9.png
  sheep_black_front-0.png
  sheep_black_front-1.png
  sheep_black_front-2.png
  sheep_black_front-3.png
  sheep_black_front-4.png
  sheep_black_front-5.png
  sheep_black_front-6.png
  sheep_black_front-7.png
  sheep_black_front-8.png
  sheep_black_idle-0.png
  sheep_black_idle-1.png
  sheep_black_idle-10.png
  sheep_black_idle-11.png
  sheep_black_idle-2.png
  sheep_black_idle-3.png
  sheep_black_idle-4.png
  sheep_black_idle-5.png
  sheep_black_idle-6.png
  sheep_black_idle-7.png
  sheep_black_idle-8.png
  sheep_black_idle-9.png
  sheep_black_puke-0.png
  sheep_black_puke-1.png
  sheep_black_puke-10.png
  sheep_black_puke-11.png
  sheep_black_puke-12.png
  sheep_black_puke-13.png
  sheep_black_puke-14.png
  sheep_black_puke-15.png
  sheep_black_puke-16.png
  sheep_black_puke-17.png
  sheep_black_puke-18.png
  sheep_black_puke-19.png
  sheep_black_puke-2.png
  sheep_black_puke-20.png
  sheep_black_puke-21.png
  sheep_black_puke-22.png
  sheep_black_puke-23.png
  sheep_black_puke-24.png
  sheep_black_puke-25.png
  sheep_black_puke-26.png
  sheep_black_puke-27.png
  sheep_black_puke-28.png
  sheep_black_puke-29.png
  sheep_black_puke-3.png
  sheep_black_puke-30.png
  sheep_black_puke-31.png
  sheep_black_puke-4.png
  sheep_black_puke-5.png
  sheep_black_puke-6.png
  sheep_black_puke-7.png
  sheep_black_puke-8.png
  sheep_black_puke-9.png
  sheep_black_walk-0.png
  sheep_black_walk-1.png
  sheep_black_walk-2.png
  sheep_black_walk-3.png
  sheep_black_walk-4.png
  sheep_black_walk-5.png
  sheep_black_walk-6.png
  sheep_black_walk-7.png
  shiba_front-0.png
  trex_front-0.png
  trex_yellow_drag-0.png
  trex_yellow_drag-1.png
  trex_yellow_drag-2.png
  trex_yellow_drag-3.png
  trex_yellow_drag-4.png
  trex_yellow_drag-5.png
  trex_yellow_drag-6.png
  trex_yellow_drag-7.png
  trex_yellow_eat-0.png
  trex_yellow_eat-1.png
  trex_yellow_eat-2.png
  trex_yellow_eat-3.png
  trex_yellow_eat-4.png
  trex_yellow_eat-5.png
  trex_yellow_eat-6.png
  trex_yellow_eat-7.png
  trex_yellow_eat-8.png
  trex_yellow_eat-9.png
  trex_yellow_fireball-0.png
  trex_yellow_fireball-1.png
  trex_yellow_fireball-10.png
  trex_yellow_fireball-11.png
  trex_yellow_fireball-12.png
  trex_yellow_fireball-2.png
  trex_yellow_fireball-3.png
  trex_yellow_fireball-4.png
  trex_yellow_fireball-5.png
  trex_yellow_fireball-6.png
  trex_yellow_fireball-7.png
  trex_yellow_fireball-8.png
  trex_yellow_fireball-9.png
  trex_yellow_front_still-0.png
  trex_yellow_front_still-1.png
  trex_yellow_front_still-2.png
  trex_yellow_front_still-3.png
  trex_yellow_front_still-4.png
  trex_yellow_front_still-5.png
  trex_yellow_front-0.png
  trex_yellow_front-1.png
  trex_yellow_front-10.png
  trex_yellow_front-11.png
  trex_yellow_front-12.png
  trex_yellow_front-13.png
  trex_yellow_front-14.png
  trex_yellow_front-2.png
  trex_yellow_front-3.png
  trex_yellow_front-4.png
  trex_yellow_front-5.png
  trex_yellow_front-6.png
  trex_yellow_front-7.png
  trex_yellow_front-8.png
  trex_yellow_front-9.png
  trex_yellow_guitar-0.png
  trex_yellow_guitar-1.png
  trex_yellow_guitar-10.png
  trex_yellow_guitar-11.png
  trex_yellow_guitar-12.png
  trex_yellow_guitar-13.png
  trex_yellow_guitar-14.png
  trex_yellow_guitar-15.png
  trex_yellow_guitar-16.png
  trex_yellow_guitar-17.png
  trex_yellow_guitar-18.png
  trex_yellow_guitar-2.png
  trex_yellow_guitar-3.png
  trex_yellow_guitar-4.png
  trex_yellow_guitar-5.png
  trex_yellow_guitar-6.png
  trex_yellow_guitar-7.png
  trex_yellow_guitar-8.png
  trex_yellow_guitar-9.png
  trex_yellow_idle-0.png
  trex_yellow_idle-1.png
  trex_yellow_idle-10.png
  trex_yellow_idle-11.png
  trex_yellow_idle-12.png
  trex_yellow_idle-13.png
  trex_yellow_idle-14.png
  trex_yellow_idle-15.png
  trex_yellow_idle-16.png
  trex_yellow_idle-17.png
  trex_yellow_idle-18.png
  trex_yellow_idle-19.png
  trex_yellow_idle-2.png
  trex_yellow_idle-3.png
  trex_yellow_idle-4.png
  trex_yellow_idle-5.png
  trex_yellow_idle-6.png
  trex_yellow_idle-7.png
  trex_yellow_idle-8.png
  trex_yellow_idle-9.png
  trex_yellow_roar-0.png
  trex_yellow_roar-1.png
  trex_yellow_roar-10.png
  trex_yellow_roar-11.png
  trex_yellow_roar-12.png
  trex_yellow_roar-13.png
  trex_yellow_roar-2.png
  trex_yellow_roar-3.png
  trex_yellow_roar-4.png
  trex_yellow_roar-5.png
  trex_yellow_roar-6.png
  trex_yellow_roar-7.png
  trex_yellow_roar-8.png
  trex_yellow_roar-9.png
  trex_yellow_selfie-0.png
  trex_yellow_selfie-1.png
  trex_yellow_selfie-10.png
  trex_yellow_selfie-2.png
  trex_yellow_selfie-3.png
  trex_yellow_selfie-4.png
  trex_yellow_selfie-5.png
  trex_yellow_selfie-6.png
  trex_yellow_selfie-7.png
  trex_yellow_selfie-8.png
  trex_yellow_selfie-9.png
  trex_yellow_texting-0.png
  trex_yellow_texting-1.png
  trex_yellow_texting-10.png
  trex_yellow_texting-11.png
  trex_yellow_texting-12.png
  trex_yellow_texting-13.png
  trex_yellow_texting-14.png
  trex_yellow_texting-15.png
  trex_yellow_texting-16.png
  trex_yellow_texting-17.png
  trex_yellow_texting-18.png
  trex_yellow_texting-19.png
  trex_yellow_texting-2.png
  trex_yellow_texting-3.png
  trex_yellow_texting-4.png
  trex_yellow_texting-5.png
  trex_yellow_texting-6.png
  trex_yellow_texting-7.png
  trex_yellow_texting-8.png
  trex_yellow_texting-9.png
  trex_yellow_walk-0.png
  trex_yellow_walk-1.png
  trex_yellow_walk-2.png
  trex_yellow_walk-3.png
  trex_yellow_walk-4.png
  trex_yellow_walk-5.png
]

assets_dir = './assets/pets/'
pets_assets_dir = '../../PetsAssets/'
FileUtils.mkdir_p(assets_dir) unless Dir.exist?(assets_dir)

assets.each do |asset|
  FileUtils.cp("#{pets_assets_dir}/#{asset}", assets_dir)
end
